# Workflow name
name: code_quality-actions

# Events which trigger the workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Jobs to be run
jobs:

  # Runs the code quality checks
  code-quality-check:
    name: Code quality check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ricardochaves/python-lint@v1.3.0
        with:
          use-black: true
          use-isort: true
          use-flake8: true

